server:
  port: 8082
  servlet:
    context-path: /notification
spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer:  org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  notification:
    email:
      brevo-url: https://api.brevo.com
      brevo-apikey: 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
      sender-name: Dev Huu Thinh
      sender-email: thinhnguyen23052004@gmail.com
